novmms/api/rest/urls.py
from django.conf import urls

urlpatterns = []


# to register the URLs for your API endpoints, decorate the view class with
# @register below, and the import the endpoint module in the
# rest_api/__init__.py module
def register(view):
    '''Register API views to respond to a regex pattern (url_regex on the
    view class).

    The view should be a standard Django class-based view implementing an
    as_view() method. The url_regex attribute of the view should be a standard
    Django URL regex pattern.
    '''
    p = urls.url(view.url_regex, view.as_view())
#    p.add_prefix('openstack_dashboard.rest_api')
    urlpatterns.append(p)
    return view

novmms/auth/urls.py
from django.conf.urls import url
from novmms.auth import views

urlpatterns = [
    url(r"^login/$", views.login, name='login'),
    url(r"^logout/$", views.logout, name='logout'),
]

novmms/dashboard/volumes/urls.py
from django.conf.urls import url

from novmms.dashboard.volumes import views

VOLUMES = r'^(?P<volume_id>[^/]+)/%s$'

urlpatterns = [
    url(r'^/*$', views.index, name='index'),
    url(r'^create/$', views.create, name='create'),
    url(VOLUMES % 'delete', views.delete, name='delete'),
    url(VOLUMES % 'attach', views.attach, name='attach'),
    url(VOLUMES % 'detach', views.detach, name='detach'),
    url(VOLUMES % 'create_snapshot', views.create_snapshot, name='create_snapshot'),
    url(VOLUMES % 'migrate', views.migrate, name='migrate'),
    url(VOLUMES % 'detail', views.detail, name='detail'),
]

novmms/urls.py
from django.conf.urls import include, url
from novmms.auth.forms import Login

# patch admin
from django.contrib import admin
admin.site.login_form = Login
from django.contrib.admin import models as admin_models
def log_action(*args, **kwargs): # disable django_admin_log(Or can't change obj on the admin)
    pass
admin_models.LogEntryManager.log_action = log_action

# patch:
from openstack_auth import utils
utils.patch_middleware_get_user()

from django.utils import functional
from django.contrib.auth import decorators
# def my_permission_required():
#     return functional.curry(decorators.permission_required,
#                             login_url='/auth/logout', raise_exception=True)
decorators.permission_required = functional.curry(decorators.permission_required,
                                                  raise_exception=True)

import json
from datetime import datetime
def json_serial(obj):
    """JSON serializer for objects not serializable by default json code"""
    if isinstance(obj, datetime):
        serial = obj.isoformat()
        return serial
    raise TypeError("Type not serializable")
json.dumps = functional.curry(json.dumps, default=json_serial)

# urls:
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/', include("novmms.auth.urls", namespace="auth")),
    url(r'^overview/', include("novmms.dashboard.overview.urls",
                               namespace="overview")),
    url(r'^instances/', include("novmms.dashboard.instances.urls",
                                namespace="instances")),
    url(r'^volumes/', include("novmms.dashboard.volumes.urls",
                              namespace="volumes")),
    url(r'^api/', include('novmms.api.rest.urls', namespace="api")),
]

novmms/models.py
from novmms.dashboard.instances.models import Instance

novmms/dashboard/volumes/forms.py
#coding:utf-8
from django import forms
from django.core.cache import cache
from novmms import api
from novmms.dashboard.instances.forms import SetIPForm

class CreateVolumeForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(),
        max_length=255,label=u"名称", required=True)
    availzones = forms.ChoiceField(label=u"可用域", required=True)
    snapshot_source = forms.CharField(label=u"从snapshot建立卷",required=False)
    local_to_instance = forms.CharField(label=u"与哪台虚机一块",required=False)
    size = forms.IntegerField(label=u"大小(G)", min_value=1,
                              required=True)

    def __init__(self, request, *args, **kwargs):
        super(CreateVolumeForm, self).__init__(*args, **kwargs)
        self.fields['availzones'].choices = [(az, az) for az in
                                             api.nova.availability_zone_list(request)]

novmms/api/rest/views.py
#coding=utf-8
from django.views import generic

from django.http import HttpResponseRedirect, HttpResponse
from django.template.defaultfilters import slugify
from django.utils import http as utils_http
from novmms import api
from novmms.api.rest import urls
from novmms.api.rest import utils as rest_utils
from novmms.exceptions import AjaxError

from novmms.dashboard.instances.models import Instance
from novmms.dashboard.instances.forms import LaunchInstanceForm, SetIPForm

from novmms.dashboard.volumes.forms import CreateVolumeForm

from django.conf import settings
PERMISSION_REQUIRED = settings.PERMISSION_REQUIRED

@urls.register
class Regions(generic.View):
    url_regex = r'regions/$'

    @rest_utils.ajax(authenticated = False)
    def get(self, request):
        default_region = {'url':settings.OPENSTACK_KEYSTONE_URL, 'name':"Default Region"}
        regions = getattr(settings, 'AVAILABLE_REGIONS', [])
        if not regions:
            regionList = [default_region]
        else:
            regionList = [dict([('url', r[0]), ('name', r[1])]) for r in regions]
        return {'items': regionList}

@urls.register
class Users(generic.View):
    """API for retrieving user_list
    """
    url_regex = r'users/$'

    @rest_utils.ajax(PERMISSION_REQUIRED['admin'])
    def get(self, request):
        """Get a specific project's users. Example:

        """
        if request.user.has_perm('openstack.roles.admin'):
            project = None
        else:
            project = request.user.tenant_id
        u_list = api.keystone.username_list(request, project=project)
        return {'items': [{'key': u, 'val': u} for u in u_list]}

@urls.register
class Servers(generic.View):
    """API over all servers.
    """
    url_regex = r'servers/$'

    @rest_utils.ajax(PERMISSION_REQUIRED['admin'])
    def get(self, request):
        """Get a list of servers.

        The listing result is an object with property "items". Each item is
        a server.

        Example GET:
        http://localhost/api/nova/servers
        """
        servers = api.nova.server_list(request)
        return {'items': [{'key': s.name, 'val': s.id} for s in servers]}

    @rest_utils.ajax(PERMISSION_REQUIRED['admin'], data_required=True)
    def post(self, request):
        """Create new instance.
        """
        form = LaunchInstanceForm(request, request.DATA)
        if form.is_valid():
            msg = 'ok'
            data = form.cleaned_data
            count = data['count'] if data['count'] else 1
            nics = []
            hints = None
            for p in data['port_id'].split(','):
                nics.append({'port-id': p})
            if data['host'] and data['same_host']:
                msg = 'host and same_host cant be set at same time'
            if data['host']:
                try:
                    host_list = api.nova.zone_host_map(request).get(data['availzones'], [])
                except Exception as exc:
                    raise AjaxError(500, str(exc))
                if data['host'] not in host_list:
                    msg = 'Failed:host not in AZ'
                else:
                    data['availzones'] += ':' + data['host']
            if data['same_host']:
                hints = {'same_host': data['same_host']}
            if msg == 'ok':
                try:
                    # call nova to create server
                    instance = api.nova.server_create(request,
                                                      data['name'],
                                                      data['image'],
                                                      data['flavor'],
                                                      data['keypair_name'],
                                                      None,
                                                      ['default'],
                                                      block_device_mapping=None,
                                                      block_device_mapping_v2=None,
                                                      nics=nics,
                                                      availability_zone=data['availzones'],
                                                      scheduler_hints=hints,
                                                      instance_count=count,
                                                      admin_pass=None,
                                                      disk_config=None,
                                                      config_drive=None)
                except Exception as exc:
                    raise AjaxError(500, str(exc))
                try:
                    # create this Instance in db
                    Instance.objects.create(uuid=instance.id,
                                            addresses=api.utils.format_addresses(instance.addresses),
                                            name=data['name'],
                                            key_name=data['keypair_name'],
                                            status=instance.status,
                                            power_state=api.utils.get_power_state(instance),
                                            host=data['host'],# api.nova.get_host(instance.id),
                                            availability_zone=data['availzones'],
                                            launched_at=instance.created,
                                            flavor=api.nova.flavor_list(request)[data['flavor']]['name'],
                                            image=api.glance.image_list_detailed(request)[data['image']]['name'],
                                            project=instance.tenant_id,
                                            owner=data['owner'])
                except Exception as exc:
                    raise AjaxError(500, 'Instance Create OK, Error when \
                                    write to DB. '+str(exc))
        else:
            raise AjaxError(400, 'Invalid Post Data')
        return {'item': instance.to_dict()}

# copy from dashboard/instances/views.py
# [TODO] put it to utils.py
ACTIVE_STATES = ("ACTIVE",)
def is_deleting(instance):
    task_state = getattr(instance, "OS-EXT-STS:task_state", None)
    if not task_state:
        return False
    return task_state.lower() == "deleting"
@urls.register
class Server(generic.View):
    """API for retrieving a single server
    """
    url_regex = r'servers/(?P<server_id>[^/]+|default)/$'

    @rest_utils.ajax(PERMISSION_REQUIRED['user'])
    def get(self, request, server_id):
        """Get a specific server. Example:

        """
        dataObj = Instance.objects.get(uuid=server_id)
        if request.user.has_perm('openstack.roles.leader') or dataObj.owner == request.user.username:
            instance = api.nova.server_get(request, server_id)
            instance.addresses = api.utils.format_addresses(instance.addresses)
            instance.power_state = api.utils.get_power_state(instance)
            instance.uuid = instance.id
            dataObj.addresses = instance.addresses
            dataObj.status = instance.status
            dataObj.power_state = instance.power_state
            dataObj.save()
            instance.owner = dataObj.owner
            instance.modified = dataObj.modified
            instance.availability_zone = dataObj.availability_zone
            ret = instance.to_dict()
            return ret
        else:
            return{'error': 'unauthorized'}

    @rest_utils.ajax(PERMISSION_REQUIRED['user'], data_required=True)
    def post(self, request, server_id):
        instance_id = server_id
        action = request.DATA.get('action')
        if not action:
            raise AjaxError(400, 'Invalid Post Data: missed action')
        if action == 'reboot': # reboot
            try:
                instance = api.nova.server_get(request, instance_id)
                if instance is not None:
                    if ((instance.status in ACTIVE_STATES
                         or instance.status == 'SHUTOFF')
                        and not is_deleting(instance)):
                        api.nova.server_reboot(request, instance_id, soft_reboot=False)
            except Exception as exc:
                raise AjaxError(500, str(exc))
        elif action == 'soft_reboot': # soft_reboot
            try:
                api.nova.server_reboot(request, instance_id, soft_reboot=True)
            except Exception as exc:
                raise AjaxError(500, str(exc))
        elif action == 'shutoff': # shutoff
            try:
                instance = api.nova.server_get(request, instance_id)
                if instance is not None:
                    if ((api.utils.get_power_state(instance) in ("running", "suspended"))
                        and not is_deleting(instance)):
                        api.nova.server_stop(request, instance_id)
            except Exception as exc:
                raise AjaxError(500, str(exc))
        elif action == 'start': # start
            try:
                instance = api.nova.server_get(request, instance_id)
                if instance is not None:
                    if instance.status in ("SHUTDOWN", "SHUTOFF", "CRASHED"):
                        api.nova.server_start(request, instance_id)
            except Exception as exc:
                raise AjaxError(500, str(exc))
        elif action == 'migrate': # migrate
            if not request.user.has_perm('openstack.roles.leader'):
                raise AjaxError(403, 'Not authorized')
            host = request.DATA.get('data').get('host')
            if host:
                try:
                    api.nova.server_migrate(request, instance_id, host)
                    # api.nova.server_confirm_resize(request, instance_id)
                except Exception as exc:
                    raise AjaxError(500, str(exc))
            else:
                raise AjaxError(400, 'Invalid Post Data')

novmms/dashboard/overview/views.py
#coding=utf-8
from django.utils import functional
from django.utils import timezone
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings

from novmms import api
from novmms.dashboard.instances.models import Instance

PERMISSION_REQUIRED = settings.PERMISSION_REQUIRED

@login_required
@permission_required(PERMISSION_REQUIRED['user'])
def index(request):
    """
    List the current users' volumes
    """
    errmsg = ''
    try:
        # count instances
        is_leader = request.user.has_perm('openstack.roles.leader')
        instances = []
        if is_leader:
            try:
                instances = api.nova.server_list(request, search_opts={})
            except Exception:
                instances = []
        else:
            myInstances = Instance.objects.filter(owner=request.user.username)
            for inst in myInstances:
                inst_info = api.nova.server_get(request, inst.uuid)
                inst_info.owner = inst.owner
                instances.append(inst_info)
        # count volumes
        volumes_count = 0
        volumes_size = 0
        if is_leader:
            volumes = api.cinder.volume_list(request)
            for v in volumes:
                volumes_count += 1
                volumes_size += v.size
        else:
            for inst in instances:
                for vid in getattr(inst, 'os-extended-volumes:volumes_attached', []):
                    vol = api.cinder.volume_get(request, vid['id'])
                    volumes_count += 1
                    volumes_size += vol.size
        # count cpus, ram
        compute_limits = api.nova.instance_usage(request)
        core_count = compute_limits.get('totalCoresUsed', 0)
        ram_count = compute_limits.get('totalRAMUsed', 0)
        # get quota
        quotas = {}
        if is_leader:
            tenant_id = request.user.tenant_id
            compute_quotas = api.nova.tenant_quota_get(request, tenant_id)
            storage_quotas = api.cinder.tenant_quota_get(request, tenant_id)
            quotas = {
                'instance_count': compute_quotas.instances,
                'volumes_count': storage_quotas.volumes,
                'volumes_size': storage_quotas.gigabytes,
                'core_count': compute_quotas.cores,
                'ram_count': compute_quotas.ram
            }
        usage_count = {
            'instance_count': len(instances),
            'volumes_count': volumes_count,
            'volumes_size': volumes_size,
            'core_count': core_count,
            'ram_count': ram_count
        }
    except Exception as exc:
        errmsg = str(exc)
    return render(request, 'novmms/dashboard/overview/index.html',
                  {'usage': usage_count, 'quotas': quotas, 'errmsg': errmsg})

novmms/templates/novmms/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static "novmms/css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "novmms/css/main.css" %}">
    <script src="{% static "novmms/js/jquery.min.js" %}"></script>
    <script src="{% static "novmms/js/bootstrap.min.js" %}"></script>
    <script src="{% static "novmms/js/angular.min.js" %}"></script>
    <script src="{% static "novmms/js/main.js" %}"></script>
    <title>{% block title %}{% endblock %}</title>  
</head>
<body>
{% block content %}{% endblock %}
</body>  
</html> 

novmms/templates/novmms/dashboard_base.html
{% load staticfiles %}
{% load is_in %}
{% load widget_tweaks %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="{% static "novmms/css/bootstrap.min.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "novmms/css/main.css" %}">
    	<script src="{% static "novmms/js/jquery.min.js" %}"></script>
    	<script src="{% static "novmms/js/bootstrap.min.js" %}"></script>
        <script src="{% static "novmms/js/angular.min.js" %}"></script>
        <script src="{% static "novmms/js/main.js" %}"></script>
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">VMMS</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'overview:index' %}" target="_self">概况</a></li>
                        <li><a href="{% url 'instances:index' %}" target="_self">云主机</a></li>
                        <li><a href="{% url 'volumes:index' %}" target="_self">存储卷</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a>
				您好, {{ user.username }}(权限:
				{% for r in user.roles %}
				{% if r.name|is_in:"stuff leader admin" %}
				{{ r.name }}
				{% endif %}
				{% endfor %}
				)页面时间{% now "H:i" %}
			</a></li>
                        <li><a href="{{ request.path }}?refresh=True" target="_self">强刷</a></li>
                        <li><a href="{{ request.path }}?clearcache=True" target="_self">清缓存</a></li>
                        <li><a href="{% url 'auth:logout' %}" target="_self">登出</a></li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
            <!--/.container-fluid -->
        </nav>
	{% if errmsg %}
    		<p class='text-warning'>{{ errmsg }}</p>
	{% endif %}
        {% block content %}{% endblock %}
    </body>
</html>

novmms/templates/novmms/modal.html
<!-- 模态框（Modal） -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="myModalLabel">
                    确认吗？
                </h4>
            </div>
            <div class="modal-body">
		    <p></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                </button>
                <button type="button" class="btn btn-primary" id="confirmBtn">
                    确认
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>